### ISSUE TITLE
Two TabErrors

### ISSUE THREAD

**Issue by cclauss** [facebookresearch/odin#3]
Unfortunately, Python 3 treats [tab errors](https://docs.python.org/3/library/exceptions.html#TabError) as syntax errors...

flake8 testing of https://github.com/facebookresearch/odin on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics_
```
./code/cal.py:71:104: E999 TabError: inconsistent use of tabs and spaces in indentation
	testset = torchvision.datasets.CIFAR10(root='../data', train=False, download=True, transform=transform)
                                                                                                       ^
./code/calMetric.py:37:12: E999 TabError: inconsistent use of tabs and spaces in indentation
	start = 0.1
           ^
2     E999 TabError: inconsistent use of tabs and spaces in indentation
2
```

**Comment by kobybibas** [comment]
I solved it by executing:
autopep8 -i cal*

**Comment by cclauss** [comment]
Even better do: __black .__

https://github.com/psf/black
